// Code generated by Kitex v0.9.1. DO NOT EDIT.

package uidservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	uid "rpc102/app/uid/kitex_gen/uid"user "rpc102/app/user/kitex_gen/user"

)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UidGen(ctx context.Context, Req *uid.Empty, callOptions ...callopt.Option) (r *uid.Uid, err error)
}

func (c Client) Register(ctx context.Context, Req *user.RegisterReq, callOptions ...callopt.Option) (r *user.RegisterResp, err error) {
	//TODO implement me
	panic("implement me")
}

func (c Client) Login(ctx context.Context, Req *user.LoginReq, callOptions ...callopt.Option) (r *user.LoginResp, err error) {
	//TODO implement me
	panic("implement me")
}

// NewClient creates a rpc for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUidServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a rpc for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUidServiceClient struct {
	*kClient
}

func (p *kUidServiceClient) UidGen(ctx context.Context, Req *uid.Empty, callOptions ...callopt.Option) (r *uid.Uid, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UidGen(ctx, Req)
}
