// Code generated by Kitex v0.9.1. DO NOT EDIT.

package uidservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	uid "rpc102/app/uid/kitex_gen/uid"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UidGen": kitex.NewMethodInfo(
		uidGenHandler,
		newUidGenArgs,
		newUidGenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	uidServiceServiceInfo                = NewServiceInfo()
	uidServiceServiceInfoForClient       = NewServiceInfoForClient()
	uidServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return uidServiceServiceInfo
}

// for rpc
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return uidServiceServiceInfoForStreamClient
}

// for stream rpc
func serviceInfoForClient() *kitex.ServiceInfo {
	return uidServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UidService"
	handlerType := (*uid.UidService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "uid",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func uidGenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(uid.Empty)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(uid.UidService).UidGen(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UidGenArgs:
		success, err := handler.(uid.UidService).UidGen(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UidGenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUidGenArgs() interface{} {
	return &UidGenArgs{}
}

func newUidGenResult() interface{} {
	return &UidGenResult{}
}

type UidGenArgs struct {
	Req *uid.Empty
}

func (p *UidGenArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(uid.Empty)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UidGenArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UidGenArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UidGenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UidGenArgs) Unmarshal(in []byte) error {
	msg := new(uid.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UidGenArgs_Req_DEFAULT *uid.Empty

func (p *UidGenArgs) GetReq() *uid.Empty {
	if !p.IsSetReq() {
		return UidGenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UidGenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UidGenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UidGenResult struct {
	Success *uid.Uid
}

var UidGenResult_Success_DEFAULT *uid.Uid

func (p *UidGenResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(uid.Uid)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UidGenResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UidGenResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UidGenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UidGenResult) Unmarshal(in []byte) error {
	msg := new(uid.Uid)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UidGenResult) GetSuccess() *uid.Uid {
	if !p.IsSetSuccess() {
		return UidGenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UidGenResult) SetSuccess(x interface{}) {
	p.Success = x.(*uid.Uid)
}

func (p *UidGenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UidGenResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UidGen(ctx context.Context, Req *uid.Empty) (r *uid.Uid, err error) {
	var _args UidGenArgs
	_args.Req = Req
	var _result UidGenResult
	if err = p.c.Call(ctx, "UidGen", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
