// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.2
// source: uid.proto

package uid

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_uid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_uid_proto_rawDescGZIP(), []int{0}
}

type Uid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Uid) Reset() {
	*x = Uid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uid) ProtoMessage() {}

func (x *Uid) ProtoReflect() protoreflect.Message {
	mi := &file_uid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uid.ProtoReflect.Descriptor instead.
func (*Uid) Descriptor() ([]byte, []int) {
	return file_uid_proto_rawDescGZIP(), []int{1}
}

func (x *Uid) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_uid_proto protoreflect.FileDescriptor

var file_uid_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x0a, 0x03, 0x55, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x32, 0x2c, 0x0a, 0x0a, 0x55, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x06, 0x55, 0x69, 0x64, 0x47, 0x65, 0x6e, 0x12, 0x0a, 0x2e, 0x75, 0x69, 0x64,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x08, 0x2e, 0x75, 0x69, 0x64, 0x2e, 0x55, 0x69, 0x64,
	0x42, 0x1e, 0x5a, 0x1c, 0x72, 0x70, 0x63, 0x31, 0x30, 0x32, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x75,
	0x69, 0x64, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x75, 0x69, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uid_proto_rawDescOnce sync.Once
	file_uid_proto_rawDescData = file_uid_proto_rawDesc
)

func file_uid_proto_rawDescGZIP() []byte {
	file_uid_proto_rawDescOnce.Do(func() {
		file_uid_proto_rawDescData = protoimpl.X.CompressGZIP(file_uid_proto_rawDescData)
	})
	return file_uid_proto_rawDescData
}

var file_uid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uid_proto_goTypes = []interface{}{
	(*Empty)(nil), // 0: uid.Empty
	(*Uid)(nil),   // 1: uid.Uid
}
var file_uid_proto_depIdxs = []int32{
	0, // 0: uid.UidService.UidGen:input_type -> uid.Empty
	1, // 1: uid.UidService.UidGen:output_type -> uid.Uid
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uid_proto_init() }
func file_uid_proto_init() {
	if File_uid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uid_proto_goTypes,
		DependencyIndexes: file_uid_proto_depIdxs,
		MessageInfos:      file_uid_proto_msgTypes,
	}.Build()
	File_uid_proto = out.File
	file_uid_proto_rawDesc = nil
	file_uid_proto_goTypes = nil
	file_uid_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.1. DO NOT EDIT.

type UidService interface {
	UidGen(ctx context.Context, req *Empty) (res *Uid, err error)
}
